version: '2'
services:
  mysqldb:
    image: mysql:latest
    container_name: airsiti-mysql
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci', '--sort_buffer_size=1073741824']
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_NAME}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
      - "./etc/mysql:/etc/mysql/conf.d"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: airsiti-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST="${MYSQL_HOST}"
    restart: always
    depends_on:
      - mysqldb
