export enum MessageBodyTypeEnum {
  PARKING_CONTRACT_RENEW_EXPIRES = "PARKING_CONTRACT_RENEW_EXPIRES",
  PARKING_CONTRACT_RENEW_EXPIRED = "PARKING_CONTRACT_RENEW_EXPIRED",
  PARKING_SLOT_RESERVED = "PARKING_SLOT_RESERVED",
  PARKING_SLOT_RESERVED_EXPIRED = "PARKING_SLOT_RESERVED_EXPIRED",
  PARKING_SLOT_AVAILABLE = "PARKING_SLOT_AVAILABLE",
 }