export enum MessageCommandEnum {
  CATEGORY_INVENTORY,
  PRODUCT_INVENTORY,
  DAILY_INVENTORY,
  ORDER,
  SHIPMENT,
  DAILY_REPORT,
  DAILY_CATEGORY_REPORT,
  DAILY_PRODUCT_REPORT,
  WEEKLY_REPORT,
  MONTHLY_REPORT,
  YEARLY_REPORT,
  HELP
}